version: "2"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - 10080:80
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=php
